services:
  db:
    image: redis
    container_name: bot_redis
    restart: always
    volumes:
      - /data/
    ports:
      - "6380:6379"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 5
  zb:
    image: zbot
    container_name: zbt
    build: .
    restart: always
    depends_on:
      db:
          condition: service_healthy
